services:
  open-webui:
    profiles: [openwebui]
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data  
    ports:
      - ${WEBUI_PORT_OPENWEBUI}:8080
    environment:
      - 'OLLAMA_BASE_URL=http://${OLLAMA_SERVER}:11434'
      - 'WEBUI_SECRET_KEY=${OPENWEBUI_SECRET_KEY}'
      - 'ENABLE_WEB_SEARCH=True'
      - 'WEB_SEARCH_ENGINE=google_pse'
      - 'GOOGLE_PSE_API_KEY=${GOOGLE_PSE_API_KEY}'
      - 'GOOGLE_PSE_ENGINE_ID=${GOOGLE_PSE_ENGINE_ID}'
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: always

volumes:
  open-webui: {}
