services:
  open-webui:
    profiles: [openwebui]
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
    ports:
      - ${WEBUI_PORT_OPENWEBUI}:8080
    environment:
      - 'OLLAMA_BASE_URL=http://${OLLAMA_SERVER}:11434'
      - 'WEBUI_SECRET_KEY=${OPENWEBUI_SECRET_KEY}'
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

volumes:
  open-webui: {}
