services:
  # https://github.com/qbittorrent/qBittorrent/wiki/Installing-qBittorrent
  qbittorrent-nox:
    profiles: [arrs]
    container_name: qbittorrent-nox
    restart: always
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - QBT_EULA=accept
      - QBT_VERSION=latest
      - QBT_WEBUI_PORT=${WEBUI_PORT_QBITTORRENT}
      - TZ=${TIMEZONE}
    image: qbittorrentofficial/qbittorrent-nox:latest
    ports:
      - ${QBIT_PORT}:6881/tcp
      - ${QBIT_PORT}:6881/udp
      - ${WEBUI_PORT_QBITTORRENT}:8080/tcp
    stop_grace_period: 30m
    tty: true
    volumes:
      - ${GLOBAL_CONFIG_FOLDER}/qbittorrent-config:/config
      - ${GLOBAL_MEDIA_FOLDER}:/downloads

  # https://github.com/linuxserver/docker-radarr
  radarr:
    profiles: [arrs]
    image: linuxserver/radarr:latest
    container_name: radarr
    restart: always
    ports:
      - ${WEBUI_PORT_RADARR}:7878
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TIMEZONE}
    volumes:
      - ${GLOBAL_CONFIG_FOLDER}/radarr-config:/config
      - ${MOVIES_FOLDER}:/movies
      - ${DOWNLOAD_COMPLETE_FOLDER}:/downloads

  # https://github.com/linuxserver/docker-sonarr
  sonarr:
    profiles: [arrs]
    image: linuxserver/sonarr:latest
    container_name: sonarr
    restart: always
    ports:
      - ${WEBUI_PORT_SONARR}:8989
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TIMEZONE}
    volumes:
      - ${GLOBAL_CONFIG_FOLDER}/sonarr-config:/config
      - ${SERIES_FOLDER}:/tv
      - ${DOWNLOAD_COMPLETE_FOLDER}:/downloads

  # https://github.com/linuxserver/docker-prowlarr
  prowlarr:
    profiles: [arrs]
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    restart: always
    ports:
      - ${WEBUI_PORT_PROWLARR}:9696
    cap_add:
      - NET_ADMIN
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TIMEZONE}
    volumes:
      - ${GLOBAL_CONFIG_FOLDER}/prowlarr-config:/config

  # https://github.com/linuxserver/docker-bazarr
  bazarr:
    profiles: [arrs]
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - ${GLOBAL_CONFIG_FOLDER}/bazarr-config:/config
      - ${MOVIES_FOLDER}:/movies
      - ${SERIES_FOLDER}:/tv
    ports:
      - ${WEBUI_PORT_BAZARR}:6767
    restart: always

  # https://github.com/FlareSolverr/FlareSolverr
  flaresolverr:
    profiles: [arrs]
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=${TIMEZONE}
    ports:
      - ${FLARESOLVERR_PORT}:8191
    restart: always   

  # https://github.com/fallenbagel/jellyseerr
  jellyseerr:
    profiles: [arrs]
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - TZ=${TIMEZONE}
      - PORT=${WEBUI_PORT_JELLYSEERR}
    ports:
      - ${WEBUI_PORT_JELLYSEERR}:5055
    volumes:
      - ${GLOBAL_CONFIG_FOLDER}/jellyseerr:/app/config
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/status || exit 1
      start_period: 20s
      timeout: 3s
      interval: 15s
      retries: 3
    restart: always      
