services:
  # https://github.com/qbittorrent/qBittorrent/wiki/Installing-qBittorrent
  qbittorrent-nox:
    profiles: [arrs]
    container_name: qbittorrent-nox:latest
    restart: unless-stopped
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - QBT_EULA=accept
      - QBT_VERSION=latest
      - QBT_WEBUI_PORT=${WEBUI_PORT_QBITTORRENT}
      - TZ=${TIMEZONE}
    image: qbittorrentofficial/qbittorrent-nox:latest
    ports:
      - ${QBIT_PORT}:6881/tcp
      - ${QBIT_PORT}:6881/udp
      - ${WEBUI_PORT_QBITTORRENT}:8080/tcp
    stop_grace_period: 30m
    tty: true
    volumes:
      - ./qbit-config:/config
      - ${GLOBAL_MEDIA_FOLDER}:/downloads

  # https://github.com/linuxserver/docker-radarr
  radarr:
    profiles: [arrs]
    image: linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    ports:
      - ${WEBUI_PORT_RADARR}:7878
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TIMEZONE}
    volumes:
      - ./radarr-config:/config
      - ${MOVIES_FOLDER}:/movies
      - ${DOWNLOAD_FOLDER}:/downloads

  # https://github.com/linuxserver/docker-sonarr
  sonarr:
    profiles: [arrs]
    image: linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    ports:
      - ${WEBUI_PORT_SONARR}:8989
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TIMEZONE}
    volumes:
      - ./sonarr-config:/config
      - ${SERIES_FOLDER}:/tv
      - ${DOWNLOAD_COMPLETE_FOLDER}:/downloads

  # https://github.com/linuxserver/docker-prowlarr
  prowlarr:
    profiles: [arrs]
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    restart: unless-stopped
    ports:
      - ${WEBUI_PORT_PROWLARR}:9696
    cap_add:
      - NET_ADMIN
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TIMEZONE}
    volumes:
      - ./prowlarr-config:/config

  # https://github.com/linuxserver/docker-bazarr
  bazarr:
    profiles: [arrs]
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - ./bazarr-config:/config
      - ${MOVIES_FOLDER}:/movies
      - ${SERIES_FOLDER}:/tv #optional
    ports:
      - ${WEBUI_PORT_BAZARR}:6767
    restart: unless-stopped

  # https://github.com/FlareSolverr/FlareSolverr
  flaresolverr:
    profiles: [arrs]
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=${TIMEZONE}
    ports:
      - ${FLARESOLVERR_PORT}:8191
    restart: unless-stopped   
