volumes:
  n8n_storage:
  postgres_storage:
  qdrant_storage:

networks:
  n8n:

services:
  postgres:
    profiles: [n8n]
    image: postgres:16-alpine
    hostname: postgres
    networks: ['n8n']
    restart: unless-stopped
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - postgres_storage:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h localhost -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 10

  n8n:
    image: n8nio/n8n:latest
    networks: ['n8n']
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_USER=${POSTGRES_USER}
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD}
      - N8N_DIAGNOSTICS_ENABLED=false
      - N8N_PERSONALIZATION_ENABLED=false
      - N8N_ENCRYPTION_KEY
      - N8N_USER_MANAGEMENT_JWT_SECRET
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_LISTEN_ADDRESS=0.0.0.0
      - N8N_SECURE_COOKIE=false
    env_file:
      - path: ../.env
        required: true
    profiles: [n8n]
    hostname: n8n
    container_name: n8n
    restart: unless-stopped
    ports:
      - ${WEBUI_PORT_N8N}:5678
    volumes:
      - n8n_storage:/home/node/.n8n
      - ${GLOBAL_CONFIG_FOLDER}/n8n/shared:/data/shared
    depends_on:
      postgres:
        condition: service_healthy

  qdrant:
    profiles: [n8n]
    image: qdrant/qdrant
    hostname: qdrant
    container_name: qdrant
    networks: ['n8n']
    restart: unless-stopped
    ports:
      - ${WEBUI_PORT_QDRANT}:6333
    volumes:
      - qdrant_storage:/qdrant/storage
