services:
  netalertx:
    profiles: [netalertx]
    container_name: netalertx
    image: "jokobsk/netalertx:latest"      
    network_mode: "host"        
    restart: unless-stopped
    volumes:
      - ${GLOBAL_CONFIG_FOLDER}/netalertx/config:/app/config
      - ${GLOBAL_CONFIG_FOLDER}/netalertx/db:/app/db
      - ${GLOBAL_CONFIG_FOLDER}/netalertx/logs:/app/front/log
    environment:
      - TZ=${TIMEZONE}
      - PORT=${WEBUI_PORT_NETALERTX}
