services:
  jellyfin:
    profiles: [jellyfin]
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    network_mode: 'host'
    restart: always
    group_add:
      - '992'
      - '44'
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
      #      - JELLYFIN_PublishedServerUrl=http://192.168.1.130
    volumes:
      - ${GLOBAL_CONFIG_FOLDER}/jellyfin/config:/config
      - ${GLOBAL_CONFIG_FOLDER}/jellyfin/cache:/cache
      - ${GLOBAL_MEDIA_FOLDER}:/media
    extra_hosts:
      - "host.docker.internal:host-gateway"
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0
