# https://prometheus.io/docs/alerting/latest/notification_examples/
# https://rtfm.co.ua/en/prometheus-alertmanagers-alerts-receivers-and-routing-based-on-severity-level-and-tags/
global:
  resolve_timeout: 5m

route:
  # https://www.robustperception.io/whats-the-difference-between-group_interval-group_wait-and-repeat_interval
  group_by: ['alertname', 'cluster', 'job', 'environment', 'severity']
  repeat_interval: 24h
  group_interval: 5m
  group_wait: 10s
  receiver: 'email'

receivers:
  - name: 'email'
    email_configs:
      - to: 'youremail'
        from: 'AlertManager <youremail>'
        smarthost: 'smtp.gmail.com:587'
        require_tls: true
        auth_username: 'youremail'
        auth_password: 'youremail'
        headers:
          subject: '{{ .CommonAnnotations.title }}'
