volumes:
  etc_wireguard:

services:
  wg-easy:
    profiles: [wireguard]
    environment:
      - INSECURE=true
      - DISABLE_IPV6=true
      - WG_HOST=${SERVER_PUBLIC_IP}

    image: ghcr.io/wg-easy/wg-easy:15.1.0
    container_name: wg-easy
    volumes:
      - etc_wireguard:/etc/wireguard
      - /lib/modules:/lib/modules:ro
    ports:
      - "${WIREGUARD_PORT}:51820/udp"
      - "${WEBUI_PORT_WIREGUARD}:51821/tcp"
    restart: always
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
