services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    profiles: [nginx]
    restart: unless-stopped
    ports:
      - ${WEBUI_PORT_NGINX_80}:80 # Public HTTP Port
      - ${WEBUI_PORT_NGINX_443}:443 # Public HTTPS Port
      - ${WEBUI_PORT_NGINX_ADMIN}:81 # Admin Web Port

    environment:
      # Uncomment this if you want to change the location of
      # the SQLite DB file within the container
      # DB_SQLITE_FILE: "/data/database.sqlite"

      # Uncomment this if IPv6 is not enabled on your host
      DISABLE_IPV6: 'true'

    volumes:
      - ${GLOBAL_CONFIG_FOLDER}/nginx/data:/data
      - ${GLOBAL_CONFIG_FOLDER}/nginx/letsencrypt:/etc/letsencrypt
